  0%|          | 0/15000 [00:00<?, ?it/s]/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [114,0,0], thread: [64,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [114,0,0], thread: [65,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [114,0,0], thread: [66,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [114,0,0], thread: [67,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [114,0,0], thread: [68,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [114,0,0], thread: [69,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [114,0,0], thread: [70,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [114,0,0], thread: [71,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [114,0,0], thread: [72,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [114,0,0], thread: [73,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [114,0,0], thread: [74,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [114,0,0], thread: [75,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [114,0,0], thread: [76,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [114,0,0], thread: [77,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [114,0,0], thread: [78,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [114,0,0], thread: [79,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [114,0,0], thread: [80,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [114,0,0], thread: [81,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [114,0,0], thread: [82,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [114,0,0], thread: [83,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [114,0,0], thread: [84,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [114,0,0], thread: [85,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [114,0,0], thread: [86,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [114,0,0], thread: [87,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [114,0,0], thread: [88,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [114,0,0], thread: [89,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [114,0,0], thread: [90,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [114,0,0], thread: [91,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [114,0,0], thread: [92,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [114,0,0], thread: [93,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [114,0,0], thread: [94,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [114,0,0], thread: [95,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.

Traceback (most recent call last):
  File "/home/ordabayev/anaconda3/envs/pyro/lib/python3.7/site-packages/pyro/poutine/trace_messenger.py", line 147, in __call__
    ret = self.fn(*args, **kwargs)
  File "/home/ordabayev/anaconda3/envs/pyro/lib/python3.7/site-packages/pyro/poutine/messenger.py", line 10, in _context_wrap
    return fn(*args, **kwargs)
  File "/home/ordabayev/anaconda3/envs/pyro/lib/python3.7/site-packages/pyro/poutine/messenger.py", line 10, in _context_wrap
    return fn(*args, **kwargs)
  File "/home/ordabayev/Documents/cosmos/cosmos/models/Modelv6.py", line 158, in model
    pyro.sample("data", self.CameraUnit(locs, gain, offset).to_event(2), obs=self.data[batch_idx])
  File "/home/ordabayev/Documents/cosmos/cosmos/models/noise.py", line 14, in CameraUnit
    base_distribution = dist.Gamma(locs/gain, 1/gain)
  File "/home/ordabayev/anaconda3/envs/pyro/lib/python3.7/site-packages/torch/distributions/gamma.py", line 48, in __init__
    super(Gamma, self).__init__(batch_shape, validate_args=validate_args)
  File "/home/ordabayev/anaconda3/envs/pyro/lib/python3.7/site-packages/torch/distributions/distribution.py", line 35, in __init__
    if not constraint.check(getattr(self, param)).all():
RuntimeError: CUDA error: device-side assert triggered

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ordabayev/Documents/cosmos/cosmos/models/Modelv6.py", line 283, in epoch
    epoch_loss = self.svi.step()
  File "/home/ordabayev/anaconda3/envs/pyro/lib/python3.7/site-packages/pyro/infer/svi.py", line 100, in step
    loss = self.loss_and_grads(self.model, self.guide, *args, **kwargs)
  File "/home/ordabayev/anaconda3/envs/pyro/lib/python3.7/site-packages/pyro/infer/traceenum_elbo.py", line 376, in loss_and_grads
    for model_trace, guide_trace in self._get_traces(model, guide, *args, **kwargs):
  File "/home/ordabayev/anaconda3/envs/pyro/lib/python3.7/site-packages/pyro/infer/traceenum_elbo.py", line 299, in _get_traces
    self._guess_max_plate_nesting(model, guide, *args, **kwargs)
  File "/home/ordabayev/anaconda3/envs/pyro/lib/python3.7/site-packages/pyro/infer/elbo.py", line 97, in _guess_max_plate_nesting
    poutine.replay(model, trace=guide_trace)).get_trace(*args, **kwargs)
  File "/home/ordabayev/anaconda3/envs/pyro/lib/python3.7/site-packages/pyro/poutine/trace_messenger.py", line 169, in get_trace
    self(*args, **kwargs)
  File "/home/ordabayev/anaconda3/envs/pyro/lib/python3.7/site-packages/pyro/poutine/trace_messenger.py", line 153, in __call__
    traceback)
  File "/home/ordabayev/anaconda3/envs/pyro/lib/python3.7/site-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/home/ordabayev/anaconda3/envs/pyro/lib/python3.7/site-packages/pyro/poutine/trace_messenger.py", line 147, in __call__
    ret = self.fn(*args, **kwargs)
  File "/home/ordabayev/anaconda3/envs/pyro/lib/python3.7/site-packages/pyro/poutine/messenger.py", line 10, in _context_wrap
    return fn(*args, **kwargs)
  File "/home/ordabayev/anaconda3/envs/pyro/lib/python3.7/site-packages/pyro/poutine/messenger.py", line 10, in _context_wrap
    return fn(*args, **kwargs)
  File "/home/ordabayev/Documents/cosmos/cosmos/models/Modelv6.py", line 158, in model
    pyro.sample("data", self.CameraUnit(locs, gain, offset).to_event(2), obs=self.data[batch_idx])
  File "/home/ordabayev/Documents/cosmos/cosmos/models/noise.py", line 14, in CameraUnit
    base_distribution = dist.Gamma(locs/gain, 1/gain)
  File "/home/ordabayev/anaconda3/envs/pyro/lib/python3.7/site-packages/torch/distributions/gamma.py", line 48, in __init__
    super(Gamma, self).__init__(batch_shape, validate_args=validate_args)
  File "/home/ordabayev/anaconda3/envs/pyro/lib/python3.7/site-packages/torch/distributions/distribution.py", line 35, in __init__
    if not constraint.check(getattr(self, param)).all():
RuntimeError: CUDA error: device-side assert triggered
       Trace Shapes:                 
        Param Sites:                 
       Sample Sites:                 
         offset dist        |        
               value        |        
           gain dist        |        
               value        |        
        N_plate dist        |        
               value     16 |        
        F_plate dist        |        
               value    831 |        
             pi dist        | 2      
               value        | 2      
        junk_pi dist        | 2      
               value        | 2      
 background_loc dist        |        
               value      1 |        
background_beta dist        |        
               value      1 |        
     height_loc dist        |        
               value      1 |        
    height_beta dist        |        
               value      1 |        
          width dist        |        
               value      1 |        
     background dist 16 831 | 1 1    
               value 16 831 | 1 1    
              z dist 16 831 |        
               value 16 831 |        
              j dist 16 831 |        
               value 16 831 |        
          theta dist 16 831 | 1 1 2 2
               value 16 831 | 1 1 2 2
         height dist 16 831 | 1 1 2 2
               value 16 831 | 1 1 2 2
             x0 dist 16 831 | 1 1 2 2
               value 16 831 | 1 1 2 2
             y0 dist 16 831 | 1 1 2 2
               value 16 831 | 1 1 2 2

